server:
  port: 443
  host: "localhost"
  logs: "/var/log/expence_management/logs.log"
  tls-cert-path: "certs/cert.pem"
  tls-key-path: "certs/key.pem"

database:
  port: 5432
  sslmode: "disable"

allowed_origins:
  - "http://localhost:5173"
  - "http://localhost:5174"
  - "http://localhost:3000"
  - "https://localhost:5173"
  - "https://localhost:3000"
